### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by dennisangemi** [orporick/orporick.github.io#2]
Ciao! Segnalo solo due url nella bio di Twitter che si sono rotti

- http://orporick.github.io/2018/04/30/man
- http://orporick.github.io/2019/06/17/man

**Comment by orporick** [comment]
Grazie infinite. Mi sa che in qualche modo adesso contano 160 caratteri compresi anche gli url. Grazie davvero

**Comment by dennisangemi** [comment]
Di nulla! Adesso sembra essere tutto ok, chiudo ;)
